/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:38:33 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/BatteryCenterUI.framework/BatteryCenterUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/_UIStaticBatteryView.h>

@interface BCUIBatteryView : _UIStaticBatteryView {

	BOOL _lowBattery;

}

@property (assign,getter=isLowBattery,nonatomic) BOOL lowBattery; 
-(id)init;
-(void)setLowBattery:(BOOL)arg1 ;
-(id)initWithSizeCategory:(long long)arg1 ;
-(BOOL)isLowBattery;
@end

