/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:33:58 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/BatteryCenter.framework/BatteryCenter
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BCBatteryDeviceObservable <NSObject>
@required
-(void)addBatteryDeviceObserver:(id)arg1 queue:(id)arg2;
-(void)removeBatteryDeviceObserver:(id)arg1;

@end

