/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:35:07 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IMRemoteDaemonProtocol, OS_dispatch_queue;
#import <IMCore/IMCore-Structs.h>
@class IMRemoteObject, NSMutableDictionary, IMLocalObject, IMDaemonListener, NSMutableArray, NSProtocolChecker, NSString, NSObject, NSRecursiveLock, NSArray, NSLock;

@interface IMDaemonController : NSObject {

	id _delegate;
	IMRemoteObject<IMRemoteDaemonProtocol> * _remoteObject;
	NSMutableDictionary* _listenerMap;
	IMLocalObject* _localObject;
	IMDaemonListener* _daemonListener;
	NSMutableArray* _services;
	NSProtocolChecker* _protocol;
	NSString* _listenerID;
	NSObject<OS_dispatch_queue> * _listenerLockQueue;
	os_unfair_recursive_lock_s _remoteDaemonLock;
	NSObject<OS_dispatch_queue> * _localObjectLockQueue;
	NSObject<OS_dispatch_queue> * _remoteMessageQueue;
	NSObject<OS_dispatch_queue> * _daemonConnectionQueue;
	NSRecursiveLock* _connectionLock;
	NSArray* _servicesToAllow;
	NSArray* _servicesToDeny;
	CFRunLoopSourceRef _runLoopSource;
	NSLock* _blockingLock;
	BOOL _hasCheckedForDaemon;
	BOOL _preventReconnect;
	BOOL _inBlockingConnect;
	BOOL _acquiringDaemonConnection;
	BOOL _autoReconnect;
	BOOL _blocksConnectionAtResume;
	BOOL _hasBeenSuspended;
	unsigned _gMyFZListenerCapabilities;
	unsigned _cachedCapabilities;
	unsigned _lastUpdatedCapabilities;
	BOOL _requestingConnection;
	NSMutableDictionary* _requestQOSClassCompletionBlocks;
	/*^block*/id _prewarmingBlock;

}

@property (setter=__setCapabilities:) unsigned _capabilities;                                                  //@synthesize gMyFZListenerCapabilities=_gMyFZListenerCapabilities - In the implementation block
@property (setter=_setAutoReconnect:) BOOL _autoReconnect;                                                     //@synthesize autoReconnect=_autoReconnect - In the implementation block
@property (nonatomic,readonly) NSObject<OS_dispatch_queue> * _remoteMessageQueue;                               //@synthesize remoteMessageQueue=_remoteMessageQueue - In the implementation block
@property (setter=_setServicesToAllow:,retain) NSArray * _servicesToAllow;                                     //@synthesize servicesToAllow=_servicesToAllow - In the implementation block
@property (setter=_setServicesToDeny:,retain) NSArray * _servicesToDeny;                                       //@synthesize servicesToDeny=_servicesToDeny - In the implementation block
@property (setter=_setListenerID:,nonatomic,retain) NSString * _listenerID;                                    //@synthesize listenerID=_listenerID - In the implementation block
@property (assign,nonatomic) id delegate;                                                               //@synthesize delegate=_delegate - In the implementation block
@property (assign,setter=_setBlocksConnectionAtResume:,nonatomic) BOOL _blocksConnectionAtResume;              //@synthesize blocksConnectionAtResume=_blocksConnectionAtResume - In the implementation block
@property (nonatomic,readonly) BOOL isConnecting; 
@property (getter=isRequestingConnection,nonatomic,readonly) BOOL requestingConnection;                        //@synthesize requestingConnection=_requestingConnection - In the implementation block
@property (nonatomic,retain) NSMutableDictionary * requestQOSClassCompletionBlocks;                            //@synthesize requestQOSClassCompletionBlocks=_requestQOSClassCompletionBlocks - In the implementation block
@property (nonatomic,copy) id prewarmingBlock;                                                                 //@synthesize prewarmingBlock=_prewarmingBlock - In the implementation block
@property (nonatomic,readonly) IMDaemonListener * listener;                                                    //@synthesize daemonListener=_daemonListener - In the implementation block
@property (nonatomic,readonly) BOOL isConnected; 
@property (nonatomic,readonly) unsigned capabilities; 
+(id)sharedInstance;
+(void)_setApplicationWillTerminate;
+(id)sharedController;
+(BOOL)_applicationWillTerminate;
+(void)_blockUntilSendQueueIsEmpty;
-(BOOL)isConnected;
-(void)setQueryContext:(id)arg1 ;
-(void)sendQueryWithReply:(BOOL)arg1 query:(/*^block*/id)arg2 ;
-(void)setPrewarmingBlock:(id)arg1 ;
-(void)setRequestQOSClassCompletionBlocks:(NSMutableDictionary *)arg1 ;
-(void)_agentDidLaunchNotification:(id)arg1 ;
-(void)_listenerSetUpdated;
-(BOOL)localObjectExists;
-(BOOL)__isLocalObjectValidOnQueue:(id)arg1 ;
-(void)systemApplicationDidResume;
-(BOOL)isConnecting;
-(void)_handleDaemonException:(id)arg1 ;
-(unsigned)capabilitiesForListenerID:(id)arg1 ;
-(void)setMyPicture:(id)arg1 smallPictureData:(id)arg2 ;
-(void)disconnectFromDaemon;
-(NSString *)_listenerID;
-(BOOL)__isRemoteObjectValid;
-(void)killDaemon;
-(void)systemApplicationDidSuspend;
-(void)setDaemonLogsOutWithoutStatusListeners:(BOOL)arg1 ;
-(void)_addressBookChanged:(id)arg1 ;
-(NSArray *)_servicesToDeny;
-(void)_noteSetupComplete;
-(BOOL)removeListenerID:(id)arg1 ;
-(unsigned)_capabilities;
-(unsigned)capabilities;
-(NSObject<OS_dispatch_queue> *)_remoteMessageQueue;
-(IMDaemonListener *)listener;
-(id)init;
-(void)forwardInvocation:(id)arg1 ;
-(void)unsetQueryContext:(id)arg1 ;
-(double)_connectionTimeout;
-(void)_connectToDaemonWithLaunch:(BOOL)arg1 capabilities:(unsigned)arg2 ;
-(void)_localObjectCleanup;
-(void)_setServicesToAllow:(NSArray *)arg1 ;
-(BOOL)_makeConnectionWithLaunch:(BOOL)arg1 completionBlock:(/*^block*/id)arg2 ;
-(BOOL)setCapabilities:(unsigned)arg1 forListenerID:(id)arg2 ;
-(BOOL)_autoReconnect;
-(void)__setCapabilities:(unsigned)arg1 ;
-(void)remoteObjectDiedNotification:(id)arg1 ;
-(void)setDaemonTerminatesWithoutListeners:(BOOL)arg1 ;
-(BOOL)connectToDaemonWithLaunch:(BOOL)arg1 ;
-(void)_setAutoReconnect:(BOOL)arg1 ;
-(void)setMyStatus:(unsigned long long)arg1 message:(id)arg2 forAccount:(id)arg3 ;
-(void)systemApplicationWillEnterForeground;
-(void)listener:(id)arg1 setValue:(id)arg2 ofPersistentProperty:(id)arg3 ;
-(void)setMyStatus:(unsigned long long)arg1 message:(id)arg2 ;
-(id)prewarmingBlock;
-(NSArray *)_servicesToAllow;
-(id)delegate;
-(void)disconnectFromDaemonWithForce:(BOOL)arg1 ;
-(void)systemApplicationDidEnterBackground;
-(void)setDelegate:(id)arg1 ;
-(NSMutableDictionary *)requestQOSClassCompletionBlocks;
-(BOOL)connectToDaemonWithLaunch:(BOOL)arg1 capabilities:(unsigned)arg2 blockUntilConnected:(BOOL)arg3 ;
-(void)listener:(id)arg1 setListenerCapabilities:(unsigned)arg2 ;
-(BOOL)_acquiringDaemonConnection;
-(void)_setListenerID:(NSString *)arg1 ;
-(id)methodSignatureForSelector:(SEL)arg1 ;
-(BOOL)isRequestingConnection;
-(void)_handleReceivedQOSClassWhileServicingRequestsNotification:(id)arg1 ;
-(void)dealloc;
-(void)_setServicesToDeny:(NSArray *)arg1 ;
-(BOOL)addListenerID:(id)arg1 capabilities:(unsigned)arg2 ;
-(BOOL)connectToDaemon;
-(void)requestQOSClassOfAgentWhileServicingRequests:(/*^block*/id)arg1 ;
-(void)blockUntilConnected;
-(void)_remoteObjectCleanup;
-(BOOL)remoteObjectExists;
-(void)_setCapabilities:(unsigned)arg1 ;
-(void)sendABInformationToDaemon;
-(BOOL)consumeQueryContext:(id)arg1 ;
-(void)_setBlocksConnectionAtResume:(BOOL)arg1 ;
-(void)localObjectDiedNotification:(id)arg1 ;
-(BOOL)hasListenerForID:(id)arg1 ;
-(void)_disconnectFromDaemonWithForce:(BOOL)arg1 ;
-(BOOL)_blocksConnectionAtResume;
-(void)_blockUntilSendQueueIsEmpty;
-(void)listener:(id)arg1 setValue:(id)arg2 ofProperty:(id)arg3 ;
-(id)_remoteObject;
@end

