/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:35:08 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/
#import <IMCore/IMHandle.h>

@class NSMutableDictionary, NSHashTable, NSArray, IMBusinessNameManager;

@interface IMHandleRegistrar : NSObject {

	NSMutableDictionary* _siblingsMap;
	NSHashTable* _allIMHandles;
	NSMutableDictionary* _IDToHandlesMap;
	NSMutableDictionary* _CNIDToHandlesMap;
	IMBusinessNameManager* _businessNameManager;

}
+(instancetype)sharedInstance;
-(void)registerIMHandle:(id)arg1 ;
-(id)init;
-(void)clearSiblingCacheForIMHandle:(id)arg1 ;
-(void)_clearSiblingsCacheForIMHandle:(id)arg1 rebuildAfter:(BOOL)arg2 ;
-(id)getIDsForFinalBatch;
-(void)_addressBookChanged;
-(void)_buildSiblingsForIMHandle:(id)arg1 ;
-(void)_dumpOutAllIMHandles;
-(id)businessNameForUID:(id)arg1 updateHandler:(/*^block*/id)arg2 ;
-(id)_existingChatSiblingsForHandle:(id)arg1 ;
-(id)_accountSiblingsForHandle:(id)arg1 ;
-(void)processContactChangeHistoryEventWithHandleIDs:(id)arg1 andCNContact:(id)arg2 ;
-(void)_handleUpdateContactChangeHistoryEvent:(id)arg1 ;
-(void)_emptySiblingCacheForIMHandleGUID:(id)arg1 ;
-(void)_dumpOutAllIMHandlesForAccount:(id)arg1 ;
-(id)getIDsForAllIMHandles;
-(NSArray<IMHandle *> *)getIMHandlesForID:(NSString *)arg1 ;
-(void)_postContactChangeHistoryEventClientNotifications;
-(void)_handleDeleteContactChangeHistoryEvent:(id)arg1 ;
-(void)_handleAddContactChangeHistoryEvent:(id)arg1 ;
-(void)clearCNIDToHandlesMap;
-(id)getIDsForInitialBatch;
-(void)removeHandleFromCNIDMap:(id)arg1 withCNID:(id)arg2 ;
-(id)handlesForCNIdentifier:(id)arg1 ;
-(void)_removeIMHandleToIDToHandlesMap:(id)arg1 ;
-(void)addHandleToCNIDMap:(id)arg1 CNContact:(id)arg2 ;
-(void)unregisterIMHandle:(id)arg1 ;
-(id)CNIDToHandlesMap;
-(void)_handleDropEverythingChangeHistoryEvent;
-(id)allIMHandles;
-(id)_existingAccountSiblingsForHandle:(id)arg1 ;
-(id)_chatSiblingsForHandle:(id)arg1 ;
-(void)_addIMHandleToIDToHandlesMap:(id)arg1 ;
-(id)IDToHandlesMap;
-(id)siblingsForIMHandle:(id)arg1 ;
@end

