/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:35:07 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/IMCore.framework/IMCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IMSystemMonitorListener
@optional
-(void)systemDidWake;
-(void)systemApplicationDidResume;
-(void)systemApplicationDidSuspend;
-(void)systemDidUnlock;
-(void)systemDidBecomeIdle;
-(void)systemDidBecomeUnidle;
-(void)systemDidStartBackup;
-(void)systemWillSleep;
-(void)systemDidLeaveFirstDataProtectionLock;
-(void)systemDidLock;
-(void)systemApplicationDidBecomeActive;
-(void)screenSaverDidStart;
-(void)screenSaverDidStop;
-(void)systemDidLeaveMemoryPressure;
-(void)systemWillShutdown;
-(void)systemApplicationWillResignActive;
-(void)systemApplicationDidSuspendForEventsOnly;
-(void)systemDidStopBackup;
-(void)systemApplicationDidResumeForEventsOnly;
-(void)notificationCenterWillAppear;
-(void)systemDidFinishMigration;
-(void)notificationCenterDidDisappear;
-(void)systemRestoreStateDidChange;
-(void)systemDidFastUserSwitchOut;
-(void)systemDidFastUserSwitchIn;
-(void)systemDidLogout;
-(void)systemScreenDidPowerUp;
-(void)systemScreenDidPowerDown;
-(void)systemDidLeaveDataProtectionLock;
-(void)systemDidEnterDataProtectionLock;
-(void)systemApplicationWillEnterForeground;
-(void)screenUnlocked;
-(void)systemApplicationDidEnterBackground;
-(void)systemDidEnterMemoryPressure;
-(void)screenLocked;

@end

