/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:29:25 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CNUIPRLikenessResolver, CNUILikenessRendering, CNSchedulerProvider;
@class CNContactStore, PRPersonaStore;

@interface CNAvatarViewControllerSettings : NSObject {

	BOOL _threeDTouchEnabled;
	CNContactStore* _contactStore;
	unsigned long long _style;
	id<CNUIPRLikenessResolver> _likenessResolver;
	id<CNUILikenessRendering> _likenessRenderer;
	id<CNSchedulerProvider> _schedulerProvider;
	PRPersonaStore* _personaStore;

}

@property (nonatomic,retain) id<CNUIPRLikenessResolver> likenessResolver;              //@synthesize likenessResolver=_likenessResolver - In the implementation block
@property (nonatomic,retain) id<CNUILikenessRendering> likenessRenderer;               //@synthesize likenessRenderer=_likenessRenderer - In the implementation block
@property (nonatomic,retain) id<CNSchedulerProvider> schedulerProvider;                //@synthesize schedulerProvider=_schedulerProvider - In the implementation block
@property (nonatomic,retain) PRPersonaStore * personaStore;                            //@synthesize personaStore=_personaStore - In the implementation block
@property (nonatomic,retain) CNContactStore * contactStore;                            //@synthesize contactStore=_contactStore - In the implementation block
@property (assign,nonatomic) BOOL threeDTouchEnabled;                                  //@synthesize threeDTouchEnabled=_threeDTouchEnabled - In the implementation block
@property (assign,nonatomic) unsigned long long style;                                 //@synthesize style=_style - In the implementation block
+(id)settingsWithLikenessResolver:(id)arg1 likenessRenderer:(id)arg2 contactStore:(id)arg3 threeDTouchEnabled:(BOOL)arg4 schedulerProvider:(id)arg5 ;
+(id)settingsWithContactStore:(id)arg1 ;
+(id)settingsWithContactStore:(id)arg1 threeDTouchEnabled:(BOOL)arg2 ;
+(id)defaultSettings;
+(id)settingsWithContactStore:(id)arg1 cacheSize:(unsigned long long)arg2 threeDTouchEnabled:(BOOL)arg3 ;
+(BOOL)threeDTouchEnabledDefaultValue;
+(id)settingsWithContactStore:(id)arg1 personaStore:(id)arg2 threeDTouchEnabled:(BOOL)arg3 ;
+(id)defaultSettingsWithCacheSize:(unsigned long long)arg1 threeDTouchEnabled:(BOOL)arg2 ;
-(void)setContactStore:(CNContactStore *)arg1 ;
-(void)setLikenessResolver:(id<CNUIPRLikenessResolver>)arg1 ;
-(id<CNUIPRLikenessResolver>)likenessResolver;
-(id)initWithLikenessResolver:(id)arg1 likenessRenderer:(id)arg2 contactStore:(id)arg3 threeDTouchEnabled:(BOOL)arg4 schedulerProvider:(id)arg5 ;
-(void)setPersonaStore:(PRPersonaStore *)arg1 ;
-(void)setStyle:(unsigned long long)arg1 ;
-(unsigned long long)style;
-(id<CNSchedulerProvider>)schedulerProvider;
-(CNContactStore *)contactStore;
-(id<CNUILikenessRendering>)likenessRenderer;
-(void)setThreeDTouchEnabled:(BOOL)arg1 ;
-(BOOL)threeDTouchEnabled;
-(PRPersonaStore *)personaStore;
-(void)setSchedulerProvider:(id<CNSchedulerProvider>)arg1 ;
-(void)setLikenessRenderer:(id<CNUILikenessRendering>)arg1 ;
@end

