/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:29:23 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

//#import <ContactsUI/ContactsUI-Structs.h>
#import <UIKit/UIView.h>
#import <ContactsUI/CNContactChangesObserver.h>
#import <ContactsUI/CNAvatarCardControllerDelegate.h>
#import <ContactsUI/CNCardTransitioning.h>

@protocol CNAvatarViewDelegate, CNUILikenessRendering, CNCancelable, CNSchedulerProvider, CNAvatarViewUpdateToken;
@class UIView, UIImage, CNContactStore, PRPersonaStore, NSArray, NSIndexSet, NSString, UIImageView, UINavigationController, CNAvatarCardController, CNContact;

@interface CNAvatarView : UIView <CNContactChangesObserver, CNAvatarCardControllerDelegate, CNCardTransitioning> {

	BOOL _showsActionsOnTap;
	BOOL _showsActionsOnForcePress;
	BOOL _threeDTouchEnabled;
	BOOL _showsContactOnTap;
	BOOL _shouldUpdateMaskedAvatars;
	BOOL _allowStaleRenderingWithMatchingContextToken;
	BOOL _registeredInNotifier;
	BOOL _registeredContactAction;
	BOOL _disableCornerRadiusForAvatar;
	BOOL _autoUpdateContact;
	BOOL _asynchronousRendering;
	BOOL _allowStaleRendering;
	BOOL _allowsAnimation;
	BOOL _prohibitsPersonaFetch;
	UIView* _forcePressView;
	unsigned long long _style;
	CNContactStore* _contactStore;
	PRPersonaStore* _personaStore;
	NSArray* _contacts;
	NSIndexSet* _maskedAvatarIndices;
	NSString* _name;
	NSString* _message;
	id<CNAvatarViewDelegate> _delegate;
	id<CNUILikenessRendering> _imageRenderer;
	id<CNCancelable> _rendererToken;
	UIImageView* _imageView;
	long long _displayedImageState;
	UINavigationController* _contactViewNavigationController;
	CNAvatarCardController* _cardController;
	id<CNSchedulerProvider> _schedulerProvider;
	unsigned long long _stateCaptureHandle;
	id<CNAvatarViewUpdateToken> _groupViewConfigurationUpdateToken;
	UIImage* _overrideImage;
	long long _monogrammerStyle;
	NSString* _contextToken;

}

@property (assign,nonatomic) BOOL showsActionsOnTap; 
@property (assign,nonatomic) BOOL showsActionsOnForcePress; 
@property (nonatomic,retain) CNContact * contact; 
@property (nonatomic,retain) id<CNUILikenessRendering> imageRenderer;                                    //@synthesize imageRenderer=_imageRenderer - In the implementation block
@property (nonatomic,retain) id<CNCancelable> rendererToken;                                             //@synthesize rendererToken=_rendererToken - In the implementation block
@property (nonatomic,copy) UIImageView * imageView;                                                      //@synthesize imageView=_imageView - In the implementation block
@property (nonatomic,retain) NSIndexSet * maskedAvatarIndices;                                           //@synthesize maskedAvatarIndices=_maskedAvatarIndices - In the implementation block
@property (assign,nonatomic) BOOL shouldUpdateMaskedAvatars;                                             //@synthesize shouldUpdateMaskedAvatars=_shouldUpdateMaskedAvatars - In the implementation block
@property (assign,nonatomic) long long displayedImageState;                                              //@synthesize displayedImageState=_displayedImageState - In the implementation block
@property (nonatomic,retain) UINavigationController * contactViewNavigationController;                   //@synthesize contactViewNavigationController=_contactViewNavigationController - In the implementation block
@property (nonatomic,retain) CNAvatarCardController * cardController;                                    //@synthesize cardController=_cardController - In the implementation block
@property (nonatomic,retain) id<CNSchedulerProvider> schedulerProvider;                                  //@synthesize schedulerProvider=_schedulerProvider - In the implementation block
@property (assign,nonatomic) unsigned long long stateCaptureHandle;                                      //@synthesize stateCaptureHandle=_stateCaptureHandle - In the implementation block
@property (nonatomic,retain) id<CNAvatarViewUpdateToken> groupViewConfigurationUpdateToken;              //@synthesize groupViewConfigurationUpdateToken=_groupViewConfigurationUpdateToken - In the implementation block
@property (assign,nonatomic) BOOL allowStaleRenderingWithMatchingContextToken;                           //@synthesize allowStaleRenderingWithMatchingContextToken=_allowStaleRenderingWithMatchingContextToken - In the implementation block
@property (assign) BOOL registeredInNotifier;                                                            //@synthesize registeredInNotifier=_registeredInNotifier - In the implementation block
@property (assign) BOOL registeredContactAction;                                                         //@synthesize registeredContactAction=_registeredContactAction - In the implementation block
@property (nonatomic,retain) UIImage * overrideImage;                                                    //@synthesize overrideImage=_overrideImage - In the implementation block
@property (assign,nonatomic) BOOL disableCornerRadiusForAvatar;                                          //@synthesize disableCornerRadiusForAvatar=_disableCornerRadiusForAvatar - In the implementation block
@property (assign,nonatomic) long long monogrammerStyle;                                                 //@synthesize monogrammerStyle=_monogrammerStyle - In the implementation block
@property (nonatomic,readonly) UIImage * contentImage; 
@property (nonatomic,readonly) CGRect contentImageFrame; 
@property (assign,nonatomic) BOOL autoUpdateContact;                                                     //@synthesize autoUpdateContact=_autoUpdateContact - In the implementation block
@property (assign,nonatomic) BOOL asynchronousRendering;                                                 //@synthesize asynchronousRendering=_asynchronousRendering - In the implementation block
@property (assign,nonatomic) BOOL bypassActionValidation; 
@property (assign,nonatomic) BOOL allowStaleRendering;                                                   //@synthesize allowStaleRendering=_allowStaleRendering - In the implementation block
@property (nonatomic,retain) NSString * contextToken;                                                    //@synthesize contextToken=_contextToken - In the implementation block
@property (nonatomic,readonly) BOOL isDisplayingContent; 
@property (assign,nonatomic) BOOL allowsAnimation;                                                       //@synthesize allowsAnimation=_allowsAnimation - In the implementation block
@property (assign,nonatomic) BOOL prohibitsPersonaFetch;                                                 //@synthesize prohibitsPersonaFetch=_prohibitsPersonaFetch - In the implementation block
@property (assign,nonatomic) unsigned long long style;                                                   //@synthesize style=_style - In the implementation block
@property (nonatomic,readonly) CNContactStore * contactStore;                                            //@synthesize contactStore=_contactStore - In the implementation block
@property (nonatomic,readonly) PRPersonaStore * personaStore;                                            //@synthesize personaStore=_personaStore - In the implementation block
@property (assign,getter=isThreeDTouchEnabled,nonatomic) BOOL threeDTouchEnabled;                        //@synthesize threeDTouchEnabled=_threeDTouchEnabled - In the implementation block
@property (nonatomic,retain) NSArray * contacts;                                                         //@synthesize contacts=_contacts - In the implementation block
@property (nonatomic,copy) NSString * name;                                                              //@synthesize name=_name - In the implementation block
@property (nonatomic,copy) NSString * message;                                                           //@synthesize message=_message - In the implementation block
@property (assign,nonatomic) id<CNAvatarViewDelegate> delegate;                                   //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) BOOL showsContactOnTap;                                                     //@synthesize showsContactOnTap=_showsContactOnTap - In the implementation block
@property (nonatomic,copy) NSArray * actionCategories; 
@property (assign,nonatomic) UIView * forcePressView;                                             //@synthesize forcePressView=_forcePressView - In the implementation block
@property (nonatomic,readonly) UIView * transitioningView; 
@property (nonatomic,readonly) CGRect transitioningFrame; 
@property (nonatomic,readonly) CGRect transitioningContentFrame; 
@property (nonatomic,readonly) UIImage * transitioningImage; 
@property (nonatomic,readonly) CGRect transitioningImageFrame; 
@property (assign) BOOL transitioningImageVisible; 
@property (nonatomic,readonly) UIView * transitioningContentView; 
+(id)descriptorForRequiredKeysWithThreeDTouchEnabled:(BOOL)arg1 shouldUseCachingRenderer:(BOOL)arg2 description:(id)arg3 ;
+(id)descriptorForRequiredKeys;
+(id)descriptionForDisplayedImageState:(long long)arg1 ;
+(BOOL)defaultThreeDTouchSupport;
+(id)descriptorForRequiredKeysWithThreeDTouchEnabled:(BOOL)arg1 ;
+(unsigned long long)maxContactAvatars;
+(id)makeDescriptorForRequiredKeysWithThreeDTouchEnabled:(BOOL)arg1 shouldUseCachingRenderer:(BOOL)arg2 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(BOOL)bypassActionValidation;
-(BOOL)allowStaleRenderingWithMatchingContextToken;
-(void)setDisableCornerRadiusForAvatar:(BOOL)arg1 ;
-(void)setTransitioningImageVisible:(BOOL)arg1 ;
-(id)init;
-(BOOL)registeredContactAction;
-(void)contactDidChange:(id)arg1 ;
-(void)dismissContactViewController:(id)arg1 ;
-(BOOL)asynchronousRendering;
-(NSString *)contextToken;
-(id)updateViewWithGroupIdentity:(id)arg1 ;
-(void)setMessage:(NSString *)arg1 ;
-(void)setShowsActionsOnTap:(BOOL)arg1 ;
-(void)layoutSubviews;
-(BOOL)showsActionsOnForcePress;
-(NSString *)message;
-(void)setProhibitsPersonaFetch:(BOOL)arg1 ;
-(void)setStyle:(unsigned long long)arg1 ;
-(BOOL)transitioningImageVisible;
-(void)setEnabled:(BOOL)arg1 ;
-(id)initWithImageRenderer:(id)arg1 threeDTouchEnabled:(BOOL)arg2 contactStore:(id)arg3 style:(unsigned long long)arg4 schedulerProvider:(id)arg5 ;
-(void)setMonogrammerStyle:(long long)arg1 ;
-(void)didMoveToWindow;
-(BOOL)avatarCardController:(id)arg1 shouldShowContact:(id)arg2 ;
-(id)descriptorForRequiredKeys;
-(UIView *)forcePressView;
-(void)_setContacts:(id)arg1 ;
-(CGRect)transitioningImageFrame;
-(id)avatarCardController:(id)arg1 orderedPropertiesForProperties:(id)arg2 category:(id)arg3 ;
-(void)setContactViewNavigationController:(UINavigationController *)arg1 ;
-(void)setContacts:(NSArray *)arg1 ;
-(BOOL)registeredInNotifier;
-(void)setForcePressView:(UIView *)arg1 ;
-(void)setGroupViewConfigurationUpdateToken:(id<CNAvatarViewUpdateToken>)arg1 ;
-(void)setName:(NSString *)arg1 ;
-(void)contactDidChange;
-(void)setImageRenderer:(id<CNUILikenessRendering>)arg1 ;
-(unsigned long long)style;
-(id)initWithCoder:(id)arg1 ;
-(id<CNSchedulerProvider>)schedulerProvider;
-(void)setAllowStaleRendering:(BOOL)arg1 ;
-(void)setContact:(CNContact *)arg1 ;
-(id)currentLikenessScope;
-(void)notifyDelegateOfGroupConfigurationUpdateWithError:(id)arg1 ;
-(void)setOverrideImage:(UIImage *)arg1 ;
-(void)setDisplayedImageState:(long long)arg1 ;
-(UIImage *)contentImage;
-(NSString *)name;
-(id)updateViewWithGroupIdentity:(id)arg1 maskingContacts:(id)arg2 ;
-(CNContactStore *)contactStore;
-(void)showContact:(id)arg1 ;
-(void)avatarCardControllerWillDismiss:(id)arg1 ;
-(BOOL)allowsAnimation;
-(id<CNAvatarViewUpdateToken>)groupViewConfigurationUpdateToken;
-(id)initWithImageRenderer:(id)arg1 threeDTouchEnabled:(BOOL)arg2 contactStore:(id)arg3 ;
-(BOOL)enabled;
-(void)avatarCardControllerDidDismiss:(id)arg1 ;
-(UIImageView *)imageView;
-(void)setMaskedAvatarIndices:(NSIndexSet *)arg1 ;
-(void)setThreeDTouchEnabled:(BOOL)arg1 ;
-(BOOL)isUpdatingGroupViewConfiguration;
-(void)setImageView:(UIImageView *)arg1 ;
-(CGRect)transitioningFrame;
-(BOOL)showsContactOnTap;
-(BOOL)isThreeDTouchEnabled;
-(void)setAllowsAnimation:(BOOL)arg1 ;
-(id<CNCancelable>)rendererToken;
-(void)setAllowStaleRenderingWithMatchingContextToken:(BOOL)arg1 ;
-(BOOL)prohibitsPersonaFetch;
-(void)avatarCardControllerWillBeginPreviewInteraction:(id)arg1 ;
-(void)_updateRegistration;
-(UIImage *)overrideImage;
-(NSArray *)contacts;
-(CNAvatarView *)initWithContact:(id)arg1 ;
-(void)setAsynchronousRendering:(BOOL)arg1 ;
-(void)setRegisteredContactAction:(BOOL)arg1 ;
-(long long)monogrammerStyle;
-(void)setRegisteredInNotifier:(BOOL)arg1 ;
-(void)clearImage;
-(BOOL)shouldUpdateMaskedAvatars;
-(id<CNAvatarViewDelegate>)delegate;
-(void)_updateCardActions;
-(BOOL)autoUpdateContact;
-(void)traitCollectionDidChange:(id)arg1 ;
-(id)initWithContactStore:(id)arg1 personaStore:(id)arg2 threeDTouchEnabled:(BOOL)arg3 ;
-(void)setContextToken:(NSString *)arg1 ;
-(void)setupAvatarCardControllerIfNeeded;
-(void)setDelegate:(id<CNAvatarViewDelegate>)arg1 ;
-(void)setBypassActionValidation:(BOOL)arg1 ;
-(id)presentingViewControllerForAvatarCardController:(id)arg1 ;
-(CGRect)contentImageFrame;
-(void)setCardController:(CNAvatarCardController *)arg1 ;
-(void)setActionCategories:(NSArray *)arg1 ;
-(id<CNUILikenessRendering>)imageRenderer;
-(void)resetGroupUpdateTokenIfNeeded;
-(void)setShowsActionsOnForcePress:(BOOL)arg1 ;
-(id)imageForTransitioningToFullScreen;
-(void)setShouldUpdateMaskedAvatars:(BOOL)arg1 ;
-(CNContact *)contact;
-(long long)displayedImageState;
-(PRPersonaStore *)personaStore;
-(void)setContacts:(id)arg1 forToken:(id)arg2 ;
-(UIImage *)transitioningImage;
-(void)setStateCaptureHandle:(unsigned long long)arg1 ;
-(long long)avatarCardController:(id)arg1 presentationResultForLocation:(CGPoint)arg2 ;
-(void)dealloc;
-(BOOL)disableCornerRadiusForAvatar;
-(BOOL)allowStaleRendering;
-(void)setRendererToken:(id<CNCancelable>)arg1 ;
-(void)setAutoUpdateContact:(BOOL)arg1 ;
-(void)setSchedulerProvider:(id<CNSchedulerProvider>)arg1 ;
-(id)initWithSettings:(id)arg1 ;
-(CNAvatarCardController *)cardController;
-(CGRect)frameForAvatarAtIndex:(unsigned long long)arg1 inView:(id)arg2 ;
-(UINavigationController *)contactViewNavigationController;
-(double)_diameter;
-(BOOL)shouldUpdateWithContacts:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(NSIndexSet *)maskedAvatarIndices;
-(void)setImage:(id)arg1 state:(long long)arg2 ;
-(NSArray *)actionCategories;
-(void)_renderContactsImage;
-(unsigned long long)stateCaptureHandle;
-(void)setShowsContactOnTap:(BOOL)arg1 ;
-(UIView *)transitioningView;
-(CGRect)transitioningContentFrame;
-(BOOL)showsActionsOnTap;
-(BOOL)isDisplayingContent;
@end

