/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:29:23 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class UIView, UIImage;


@protocol CNCardTransitioning <NSObject>
@property (nonatomic,readonly) UIView * transitioningView; 
@property (nonatomic,readonly) CGRect transitioningFrame; 
@property (nonatomic,readonly) CGRect transitioningContentFrame; 
@property (nonatomic,readonly) UIImage * transitioningImage; 
@property (nonatomic,readonly) CGRect transitioningImageFrame; 
@property (assign) BOOL transitioningImageVisible; 
@property (nonatomic,readonly) UIView * transitioningContentView; 
@optional
-(UIView *)transitioningContentView;

@required
-(void)setTransitioningImageVisible:(BOOL)arg1;
-(BOOL)transitioningImageVisible;
-(CGRect)transitioningImageFrame;
-(CGRect)transitioningFrame;
-(UIImage *)transitioningImage;
-(UIView *)transitioningView;
-(CGRect)transitioningContentFrame;

@end

