/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:29:23 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/Frameworks/ContactsUI.framework/ContactsUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CNContactChangesObserver <NSObject>
@optional
-(void)contactWithIdentifierWasDeleted:(id)arg1;

@required
-(void)contactDidChange:(id)arg1;

@end

