/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:29:09 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKitCore/UIKitCore-Structs.h>
#import <UIKit/UIView.h>
#import <UIKitCore/_UIStatusBarDisplayable.h>

@class UIColor, UILabel, _UIBatteryViewAXHUDImageCacheInfo, CALayer, CAShapeLayer, UIAccessibilityHUDItem, NSString;

@interface _UIBatteryView : UIView <_UIStatusBarDisplayable> {

	BOOL _saverModeActive;
	BOOL _showsInlineChargingIndicator;
	BOOL _showsPercentage;
	UIColor* _fillColor;
	UIColor* _bodyColor;
	UIColor* _pinColor;
	UIColor* _boltColor;
	double _chargePercent;
	long long _chargingState;
	double _lowBatteryChargePercentThreshold;
	long long _iconSize;
	UILabel* _percentageLabel;
	_UIBatteryViewAXHUDImageCacheInfo* _accessibilityHUDImageCacheInfo;
	CALayer* _bodyLayer;
	CALayer* _pinLayer;
	CALayer* _boltMaskLayer;
	CALayer* _boltLayer;
	CALayer* _fillLayer;
	long long _internalSizeCategory;
	double _bodyColorAlpha;
	double _pinColorAlpha;

}

@property (assign,nonatomic) long long iconSize;                                                              //@synthesize iconSize=_iconSize - In the implementation block
@property (nonatomic,readonly) CAShapeLayer * bodyShapeLayer; 
@property (nonatomic,readonly) CAShapeLayer * pinShapeLayer; 
@property (nonatomic,readonly) CAShapeLayer * boltMaskShapeLayer; 
@property (nonatomic,readonly) CAShapeLayer * boltShapeLayer; 
@property (nonatomic,retain) UILabel * percentageLabel;                                                       //@synthesize percentageLabel=_percentageLabel - In the implementation block
@property (nonatomic,retain) _UIBatteryViewAXHUDImageCacheInfo * accessibilityHUDImageCacheInfo;              //@synthesize accessibilityHUDImageCacheInfo=_accessibilityHUDImageCacheInfo - In the implementation block
@property (nonatomic,retain) CALayer * bodyLayer;                                                             //@synthesize bodyLayer=_bodyLayer - In the implementation block
@property (nonatomic,retain) CALayer * pinLayer;                                                              //@synthesize pinLayer=_pinLayer - In the implementation block
@property (nonatomic,retain) CALayer * boltMaskLayer;                                                         //@synthesize boltMaskLayer=_boltMaskLayer - In the implementation block
@property (nonatomic,retain) CALayer * boltLayer;                                                             //@synthesize boltLayer=_boltLayer - In the implementation block
@property (nonatomic,retain) CALayer * fillLayer;                                                             //@synthesize fillLayer=_fillLayer - In the implementation block
@property (assign,nonatomic) long long internalSizeCategory;                                                  //@synthesize internalSizeCategory=_internalSizeCategory - In the implementation block
@property (assign,nonatomic) BOOL showsPercentage;                                                            //@synthesize showsPercentage=_showsPercentage - In the implementation block
@property (assign,nonatomic) double bodyColorAlpha;                                                           //@synthesize bodyColorAlpha=_bodyColorAlpha - In the implementation block
@property (assign,nonatomic) double pinColorAlpha;                                                            //@synthesize pinColorAlpha=_pinColorAlpha - In the implementation block
@property (assign,nonatomic) long long sizeCategory; 
@property (assign,nonatomic) double chargePercent;                                                            //@synthesize chargePercent=_chargePercent - In the implementation block
@property (assign,nonatomic) long long chargingState;                                                         //@synthesize chargingState=_chargingState - In the implementation block
@property (assign,nonatomic) BOOL saverModeActive;                                                            //@synthesize saverModeActive=_saverModeActive - In the implementation block
@property (assign,nonatomic) double lowBatteryChargePercentThreshold;                                         //@synthesize lowBatteryChargePercentThreshold=_lowBatteryChargePercentThreshold - In the implementation block
@property (getter=isLowBattery,nonatomic,readonly) BOOL lowBattery; 
@property (assign,nonatomic) BOOL showsInlineChargingIndicator;                                               //@synthesize showsInlineChargingIndicator=_showsInlineChargingIndicator - In the implementation block
@property (nonatomic,copy) UIColor * fillColor;                                                               //@synthesize fillColor=_fillColor - In the implementation block
@property (nonatomic,copy) UIColor * bodyColor;                                                               //@synthesize bodyColor=_bodyColor - In the implementation block
@property (nonatomic,copy) UIColor * pinColor;                                                                //@synthesize pinColor=_pinColor - In the implementation block
@property (nonatomic,copy) UIColor * boltColor;                                                               //@synthesize boltColor=_boltColor - In the implementation block
@property (nonatomic,readonly) BOOL wantsCrossfade; 
@property (nonatomic,readonly) BOOL prefersBaselineAlignment; 
@property (nonatomic,readonly) long long overriddenVerticalAlignment; 
@property (nonatomic,readonly) UIAccessibilityHUDItem * accessibilityHUDRepresentation;

+(id)_boltMaskBezierPath;
+(id)_boltBezierPathForSize:(CGSize)arg1 ;
+(id)_pinBezierPathForSize:(CGSize)arg1 complex:(BOOL)arg2 ;
+(CGSize)_pinSizeForIconSize:(long long)arg1 ;
+(CGSize)_batterySizeForIconSize:(long long)arg1 ;
+(double)_lineWidthAndInterspaceForIconSize:(long long)arg1 ;
+(CGSize)_statusBarIntrinsicContentSizeForIconSize:(long long)arg1 ;
-(long long)iconSize;
-(void)setFillColor:(UIColor *)arg1 ;
-(UIColor *)fillColor;
-(void)applyStyleAttributes:(id)arg1 ;
-(UIAccessibilityHUDItem *)accessibilityHUDRepresentation;
-(void)_commonInit;
-(void)layoutSubviews;
-(void)setIconSize:(long long)arg1 ;
-(BOOL)_shouldShowBolt;
-(void)setSizeCategory:(long long)arg1 ;
-(CALayer *)pinLayer;
-(UIColor *)pinColor;
-(void)_updateFillLayer;
-(void)setBodyLayer:(CALayer *)arg1 ;
-(id)_batteryFillColor;
-(void)setBoltMaskLayer:(CALayer *)arg1 ;
-(CGSize)intrinsicContentSize;
-(long long)internalSizeCategory;
-(CGRect)_bodyRectForTraitCollection:(id)arg1 ;
-(CGSize)_pinSizeForTraitCollection:(id)arg1 ;
-(double)_batteryBoltScaleFactorMultiplier;
-(double)_lineWidthAndInterspaceForTraitCollection:(id)arg1 ;
-(CGRect)_updateBodyLayers;
-(double)_outsideCornerRadiusForTraitCollection:(id)arg1 ;
-(CGSize)_batterySizeForTraitCollection:(id)arg1 ;
-(void)_fillLayerFrame:(CGRect*)arg1 cornerRadius:(double*)arg2 ;
-(id)initWithCoder:(id)arg1 ;
-(double)_batteryBoltLargeScaleFactor;
-(void)_createFillLayer;
-(void)_updateBatteryFillColor;
-(long long)sizeCategory;
-(void)_updateTransform;
-(void)setSaverModeActive:(BOOL)arg1 ;
-(CALayer *)bodyLayer;
-(CALayer *)fillLayer;
-(UIColor *)bodyColor;
-(UIColor *)boltColor;
-(CALayer *)boltLayer;
-(void)setChargePercent:(double)arg1 ;
-(void)setShowsPercentage:(BOOL)arg1 ;
-(void)setBodyColorAlpha:(double)arg1 ;
-(void)setPinColorAlpha:(double)arg1 ;
-(void)setShowsInlineChargingIndicator:(BOOL)arg1 ;
-(void)setInternalSizeCategory:(long long)arg1 ;
-(void)_createBoltLayersWithSize:(CGSize)arg1 ;
-(void)setLowBatteryChargePercentThreshold:(double)arg1 ;
-(CAShapeLayer *)bodyShapeLayer;
-(CAShapeLayer *)boltMaskShapeLayer;
-(CAShapeLayer *)boltShapeLayer;
-(BOOL)_currentlyShowsPercentage;
-(void)__updateFillLayer;
-(CAShapeLayer *)pinShapeLayer;
-(id)_batteryTextColor;
-(void)_updateFillColor;
-(double)chargePercent;
-(double)_insideCornerRadiusForTraitCollection:(id)arg1 ;
-(void)_unflipBoltIfNecessary;
-(void)_notifyWillBeginAnimatingBoltToVisible:(BOOL)arg1 ;
-(void)_notifyDidFinishAnimatingBoltToVisible:(BOOL)arg1 ;
-(void)__resetBoltLayers;
-(void)setPinColor:(UIColor *)arg1 ;
-(void)_updatePercentage;
-(double)lowBatteryChargePercentThreshold;
-(void)setBodyColor:(UIColor *)arg1 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(_UIBatteryViewAXHUDImageCacheInfo *)accessibilityHUDImageCacheInfo;
-(void)setAccessibilityHUDImageCacheInfo:(_UIBatteryViewAXHUDImageCacheInfo *)arg1 ;
-(id)initWithSizeCategory:(long long)arg1 ;
-(void)setBoltColor:(UIColor *)arg1 ;
-(BOOL)showsInlineChargingIndicator;
-(UILabel *)percentageLabel;
-(void)setPercentageLabel:(UILabel *)arg1 ;
-(BOOL)showsPercentage;
-(double)bodyColorAlpha;
-(double)pinColorAlpha;
-(long long)chargingState;
-(BOOL)saverModeActive;
-(void)_willBeginAnimatingBoltToVisible:(BOOL)arg1 ;
-(double)_batteryBoltSmallScaleFactor;
-(void)setChargingState:(long long)arg1 ;
-(void)_updateBodyColors;
-(void)setPinLayer:(CALayer *)arg1 ;
-(void)_didFinishAnimatingBoltToVisible:(BOOL)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)_updateBolt;
-(void)setFillLayer:(CALayer *)arg1 ;
-(void)setBoltLayer:(CALayer *)arg1 ;
-(CALayer *)boltMaskLayer;
-(void)_createBodyLayers;
-(BOOL)isLowBattery;
@end

