/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:28:54 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class UIAccessibilityHUDItem;


@protocol _UIStatusBarDisplayable <NSObject>
@property (nonatomic,readonly) BOOL wantsCrossfade; 
@property (nonatomic,readonly) BOOL prefersBaselineAlignment; 
@property (nonatomic,readonly) long long overriddenVerticalAlignment; 
@property (nonatomic,readonly) UIAccessibilityHUDItem * accessibilityHUDRepresentation; 
@optional
-(BOOL)prefersBaselineAlignment;
-(void)applyStyleAttributes:(id)arg1;
-(UIAccessibilityHUDItem *)accessibilityHUDRepresentation;
-(long long)overriddenVerticalAlignment;
-(BOOL)wantsCrossfade;

@end

