/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:36:24 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/SpringBoard.framework/SpringBoard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SpringBoardUI/SBAlertItem.h>

@interface SBLowPowerAlertItem : SBAlertItem {

	unsigned _talkLevel;

}
+(void)initialize;
+(void)setBatteryLevel:(unsigned)arg1 ;
+(unsigned)_thresholdForLevel:(unsigned)arg1 ;
+(BOOL)_shouldIgnoreChangeToBatteryLevel:(unsigned)arg1 ;
-(BOOL)shouldShowInLockScreen;
-(id)init;
-(id)initWithLevel:(unsigned)arg1 ;
-(void)configure:(BOOL)arg1 requirePasscodeForActions:(BOOL)arg2 ;
-(BOOL)wakeDisplay;
-(BOOL)shouldShowInEmergencyCall;
-(void)_enableLowPowerMode;
@end

