/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:36:06 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

typedef struct _NSZone* NSZoneRef;

typedef struct {
	float opacity;
	CGSize offset;
	double radius;
} SCD_Struct_MT3;

typedef struct {
	float field1;
	CGSize field2;
	double field3;
} SCD_Struct_MT4;

