/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:36:06 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol MTMaterialViewObserving <NSObject>
@optional
-(void)groupNameDidChangeForMaterialView:(id)arg1;
-(void)weightingDidChangeForMaterialView:(id)arg1;
-(void)configurationDidChangeForMaterialView:(id)arg1;
-(void)recipeNameDidChangeForMaterialView:(id)arg1;

@end

