/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:36:06 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MaterialKit/MaterialKit-Structs.h>
#import <UIKit/UIView.h>
#import <MaterialKit/MTMaterialView.h>
#import <MaterialKit/MTMaterialViewObserving.h>

@class UIView, UIColor, NSString;

@interface MTMaterialShadowView : UIView <MTMaterialViewObserving> {

	UIView* _shadowView;
	MTMaterialView* _captureOnlyMaterialView;
	BOOL _captureOnlyMaterialViewSuppliedByClient;
	MTMaterialView* _materialView;

}

@property (nonatomic,readonly) MTMaterialView * materialView;                                                                            //@synthesize materialView=_materialView - In the implementation block
@property (assign,getter=isCaptureOnlyMaterialViewSuppliedByClient,nonatomic) BOOL captureOnlyMaterialViewSuppliedByClient;              //@synthesize captureOnlyMaterialViewSuppliedByClient=_captureOnlyMaterialViewSuppliedByClient - In the implementation block
@property (nonatomic,copy) UIColor * shadowColor; 
@property (assign,nonatomic) double shadowOpacity; 
@property (assign,nonatomic) CGSize shadowOffset; 
@property (assign,nonatomic) double shadowRadius; 
@property (assign,nonatomic) BOOL shadowPathIsBounds; 

+(id)materialShadowViewWithRecipe:(long long)arg1 configuration:(long long)arg2 initialWeighting:(double)arg3 ;
+(id)materialShadowViewWithRecipe:(long long)arg1 configuration:(long long)arg2 initialWeighting:(double)arg3 scaleAdjustment:(/*^block*/id)arg4 ;
+(id)materialShadowViewWithRecipe:(long long)arg1 configuration:(long long)arg2 ;
+(id)materialShadowViewWithRecipeNamed:(id)arg1 inBundle:(id)arg2 configuration:(long long)arg3 initialWeighting:(double)arg4 scaleAdjustment:(/*^block*/id)arg5 ;
+(id)materialShadowViewWithRecipeNamesByTraitCollection:(id)arg1 inBundle:(id)arg2 configuration:(long long)arg3 initialWeighting:(double)arg4 scaleAdjustment:(/*^block*/id)arg5 ;
-(void)setShadowOpacity:(double)arg1 ;
-(void)_setContinuousCornerRadius:(double)arg1 ;
-(MTMaterialView *)materialView;
-(void)setShadowOffset:(CGSize)arg1 ;
-(double)shadowRadius;
-(CGSize)shadowOffset;
-(double)shadowOpacity;
-(void)setShadowRadius:(double)arg1 ;
-(void)layoutSubviews;
-(void)setShadowColor:(UIColor *)arg1 ;
-(BOOL)shadowPathIsBounds;
-(UIColor *)shadowColor;
-(void)setShadowPathIsBounds:(BOOL)arg1 ;
-(void)groupNameDidChangeForMaterialView:(id)arg1 ;
-(void)weightingDidChangeForMaterialView:(id)arg1 ;
-(void)configurationDidChangeForMaterialView:(id)arg1 ;
-(void)recipeNameDidChangeForMaterialView:(id)arg1 ;
-(id)initWithMaterialView:(id)arg1 ;
-(void)setCaptureOnlyMaterialViewSuppliedByClient:(BOOL)arg1 ;
-(void)_configureShadowViewIfNecessary;
-(void)_configureCaptureOnlyMaterialViewIfNecessary;
-(BOOL)isCaptureOnlyMaterialViewSuppliedByClient;
@end

