/*
* This header is generated by classdump-dyld 1.0
* on Friday, February 12, 2021 at 12:36:06 AM Eastern European Standard Time
* Operating System: Version 14.4 (Build 18D52)
* Image Source: /System/Library/PrivateFrameworks/MaterialKit.framework/MaterialKit
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MaterialKit/MaterialKit-Structs.h>
#import <UIKit/UIView.h>
#import <MaterialKit/MTVisualStylingProviding.h>

@class NSMutableDictionary, NSDictionary, NSBundle, NSHashTable, UIView, NSString, UIViewFloatAnimatableProperty, MTMaterialLayer;

@interface MTMaterialView : UIView <NSCopying, MTVisualStylingProviding> {

	BOOL _useBuiltInAlphaTransformerAndBackdropScaleAdjustment;
	BOOL _recipeDynamic;
	BOOL _shadowed;
	NSMutableDictionary* _cmVisualStyleCategoriesToProviders;
	NSDictionary* _recipeNamesByTraitCollection;
	NSBundle* _recipeBundle;
	NSHashTable* _observers;
	UIView* _highlightView;
	BOOL _needsLayoutOnMoveToWindow;
	BOOL _highlighted;
	NSString* _groupNameBase;
	long long _recipe;
	long long _configuration;
	UIViewFloatAnimatableProperty* _backdropFloatAnimatableProperty;

}

@property (nonatomic,copy) NSString * recipeName; 
@property (assign,getter=isBlurEnabled,nonatomic) BOOL blurEnabled; 
@property (assign,getter=isZoomEnabled,nonatomic) BOOL zoomEnabled; 
@property (assign,getter=isCaptureOnly,nonatomic) BOOL captureOnly; 
@property (assign,getter=isShadowed,nonatomic) BOOL shadowed; 
@property (assign,getter=isInPlaceFilteringEnabled,nonatomic) BOOL inPlaceFilteringEnabled; 
@property (nonatomic,copy) id backdropScaleAdjustment; 
@property (assign,nonatomic) BOOL shouldCrossfade; 
@property (assign,nonatomic) BOOL useBuiltInAlphaTransformerAndBackdropScaleAdjustment; 
@property (assign,nonatomic) BOOL useBuiltInAlphaTransformerAndBackdropScaleAdjustmentIfNecessary; 
@property (assign,getter=isRecipeDynamic,nonatomic) BOOL recipeDynamic; 
@property (assign,nonatomic) BOOL ignoresScreenClip; 
@property (assign,getter=isContentReplacedWithSnapshot,nonatomic) BOOL contentReplacedWithSnapshot; 
@property (getter=_materialLayer,nonatomic,readonly) MTMaterialLayer * materialLayer; 
@property (assign,nonatomic) BOOL shouldCrossfadeIfNecessary; 
@property (assign,nonatomic) BOOL forceCrossfadeIfNecessary; 
@property (getter=_backdropFloatAnimatableProperty,nonatomic,retain) UIViewFloatAnimatableProperty * backdropFloatAnimatableProperty;              //@synthesize backdropFloatAnimatableProperty=_backdropFloatAnimatableProperty - In the implementation block
@property (nonatomic,copy) NSString * groupName; 
@property (nonatomic,copy) NSString * groupNameBase;                                                                                               //@synthesize groupNameBase=_groupNameBase - In the implementation block
@property (assign,nonatomic) double weighting; 
@property (assign,nonatomic) long long recipe;                                                                                                     //@synthesize recipe=_recipe - In the implementation block
@property (assign,nonatomic) long long configuration;                                                                                              //@synthesize configuration=_configuration - In the implementation block
@property (assign,getter=isHighlighted,nonatomic) BOOL highlighted;                                                                                //@synthesize highlighted=_highlighted - In the implementation block

+(void)initialize;
+(id)_recipeNameForTraitCollection:(id)arg1 withRecipeNamesByTraitCollection:(id)arg2 ;
+(id)newDefaultHighlightAnimator;
+(id)materialViewWithRecipe:(long long)arg1 configuration:(long long)arg2 initialWeighting:(double)arg3 ;
+(id)materialViewWithRecipeNamesByTraitCollection:(id)arg1 inBundle:(id)arg2 configuration:(long long)arg3 initialWeighting:(double)arg4 scaleAdjustment:(/*^block*/id)arg5 ;
+(Class)layerClass;
+(id)materialViewWithRecipe:(long long)arg1 configuration:(long long)arg2 initialWeighting:(double)arg3 compatibleWithTraitCollection:(id)arg4 ;
+(id)materialViewWithRecipeNamed:(id)arg1 inBundle:(id)arg2 configuration:(long long)arg3 initialWeighting:(double)arg4 scaleAdjustment:(/*^block*/id)arg5 ;
+(id)staticMaterialViewWithRecipe:(long long)arg1 configuration:(long long)arg2 ;
+(id)materialViewWithRecipe:(long long)arg1 configuration:(long long)arg2 initialWeighting:(double)arg3 scaleAdjustment:(/*^block*/id)arg4 ;
+(id)materialViewWithRecipeNamed:(id)arg1 ;
+(id)materialViewWithRecipeNamesByTraitCollection:(id)arg1 compatibleWithTraitCollection:(id)arg2 bundle:(id)arg3 configuration:(long long)arg4 initialWeighting:(double)arg5 scaleAdjustment:(/*^block*/id)arg6 ;
+(id)materialViewWithRecipe:(long long)arg1 configuration:(long long)arg2 ;
-(BOOL)isHighlighted;
-(BOOL)isZoomEnabled;
-(double)weighting;
-(void)setZoomEnabled:(BOOL)arg1 ;
-(BOOL)isBlurEnabled;
-(void)setShouldCrossfadeIfNecessary:(BOOL)arg1 ;
-(void)setWeighting:(double)arg1 ;
-(void)setBackdropScaleAdjustment:(id)arg1 ;
-(id)init;
-(void)setContentReplacedWithSnapshot:(BOOL)arg1 ;
-(void)setRecipeDynamic:(BOOL)arg1 ;
-(void)setInPlaceFilteringEnabled:(BOOL)arg1 ;
-(void)setConfiguration:(long long)arg1 ;
-(NSString *)groupName;
-(id)_backdropFloatAnimatableProperty;
-(void)_removeObserver:(id)arg1 ;
-(void)layoutSubviews;
-(void)setGroupName:(NSString *)arg1 ;
-(BOOL)shouldCrossfade;
-(id)newShadowView;
-(void)setBlurEnabled:(BOOL)arg1 ;
-(void)didMoveToWindow;
-(void)setDebugIdentifier:(NSString *)arg1 ;
-(void)_reduceTransparencyStatusDidChange;
-(BOOL)_shouldAnimatePropertyWithKey:(id)arg1 ;
-(id)_initWithCoreMaterialRecipe:(id)arg1 fromBundle:(id)arg2 coreMaterialConfiguration:(id)arg3 initialWeighting:(double)arg4 scaleAdjustment:(/*^block*/id)arg5 ;
-(BOOL)ignoresScreenClip;
-(BOOL)isManagingInterpolationForMaterialLayer:(id)arg1 ;
-(BOOL)isShadowed;
-(void)setGroupNameBase:(NSString *)arg1 ;
-(id)visualStylingProviderForCategory:(long long)arg1 ;
-(void)_setupOrInvalidateAlphaTransformer;
-(BOOL)useBuiltInAlphaTransformerAndBackdropScaleAdjustmentIfNecessary;
-(void)_updateGroupNameIfNecessary;
-(void)setRecipe:(long long)arg1 ;
-(void)_reduceMotionStatusDidChange;
-(id)_materialLayer;
-(BOOL)useBuiltInAlphaTransformerAndBackdropScaleAdjustment;
-(void)setRecipeName:(NSString *)arg1 ;
-(NSString *)debugIdentifier;
-(long long)recipe;
-(BOOL)addCompletionForCurrentAnimation:(/*^block*/id)arg1 forMaterialLayer:(id)arg2 reason:(out id*)arg3 ;
-(id)_initWithRecipeNamesByTraitCollection:(id)arg1 compatibleWithTraitCollection:(id)arg2 bundle:(id)arg3 configuration:(long long)arg4 initialWeighting:(double)arg5 scaleAdjustment:(/*^block*/id)arg6 ;
-(BOOL)isManagingOpacityForMaterialLayer:(id)arg1 ;
-(void)_addObserver:(id)arg1 ;
-(id)backdropScaleAdjustment;
-(void)_notifyObserversWithBlock:(/*^block*/id)arg1 ;
-(void)setUseBuiltInAlphaTransformerAndBackdropScaleAdjustment:(BOOL)arg1 ;
-(void)setShouldCrossfade:(BOOL)arg1 ;
-(long long)configuration;
-(void)_setRecipeName:(id)arg1 withWeighting:(double)arg2 ;
-(id)_initWithRecipe:(long long)arg1 configuration:(long long)arg2 userInterfaceStyle:(long long)arg3 initialWeighting:(double)arg4 scaleAdjustment:(/*^block*/id)arg5 ;
-(void)setCaptureOnly:(BOOL)arg1 ;
-(void)setHighlighted:(BOOL)arg1 ;
-(void)setUseBuiltInAlphaTransformerAndBackdropScaleAdjustmentIfNecessary:(BOOL)arg1 ;
-(void)setShadowed:(BOOL)arg1 ;
-(BOOL)managesWeightingForMaterialLayer:(id)arg1 ;
-(NSString *)description;
-(id)_coreMaterialVisualStylingProviderForCategory:(id)arg1 ;
-(BOOL)isInPlaceFilteringEnabled;
-(id)newShadowViewWithCaptureOnlyMaterialView:(BOOL)arg1 ;
-(void)dealloc;
-(id)_recipeNameForCurrentTraitCollection;
-(BOOL)isContentReplacedWithSnapshot;
-(void)prune;
-(void)setForceCrossfadeIfNecessary:(BOOL)arg1 ;
-(NSString *)groupNameBase;
-(BOOL)forceCrossfadeIfNecessary;
-(BOOL)shouldCrossfadeIfNecessary;
-(BOOL)isRecipeDynamic;
-(void)setBackdropFloatAnimatableProperty:(UIViewFloatAnimatableProperty *)arg1 ;
-(BOOL)isCaptureOnly;
-(void)setIgnoresScreenClip:(BOOL)arg1 ;
-(void)_invalidateAlphaTransformer;
-(id)_groupNameWithBase:(id)arg1 ;
-(void)_updateRecipeNameIfNeeded;
-(void)_setupAlphaTransformer;
-(NSString *)recipeName;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

